export const HOME_PAGE_TITLE = "Home"

// table 
export const HOME_PAGE_TABLE_MUSIC_NAME = "Name"
export const HOME_PAGE_TABLE_RELEASE_TIME = "Release time"
export const HOME_PAGE_TABLE_GENRE = "Genre"
export const HOME_PAGE_TABLE_MUSICIAN = "Musician"
export const HOME_PAGE_TABLE_SINGER = "Singer"
export const HOME_PAGE_MODAL_MUSIC_NAME = "Name"
export const HOME_PAGE_MODAL_RELEASE_TIME = "Release time"
export const HOME_PAGE_MODAL_GENRE = "Genre"
export const HOME_PAGE_MODAL_MUSICIAN = "Select musician | "
export const HOME_PAGE_MODAL_SINGER =  "Select singer | "
export const HOME_PAGE_MODAL_TITLE_ADD_MUSIC = "Add music"
export const HOME_PAGE_MODAL_TITLE_MODIFY_MUSIC = "Modify music"
export const HOME_PAGE_MODAL_BUTTON_ADD = "Add"
export const HOME_PAGE_MODAL_BUTTON_MODIFY = "Modify"
export const HOME_PAGE_MODAL_BUTTON_CLOSE = "Close"